### ISSUE TITLE
Allowing users to set the sample size needed to pass the split frequency difference

### ISSUE THREAD

**Issue by hoehna** [lfabreti/convenience#2]
add a user option for this

**Comment by lfabreti** [comment]
I calculate the minimum ESS according with the precision the user sets for the standard error of the mean
For the KS threshold and the expected difference of split frequencies, I am using the minimum ESS divided by 5, because I split the run into 5 windows
Is that ok?

**Comment by hoehna** [comment]
That should be fine as long as it is documented that way.
