### ISSUE TITLE
checkConvergence() error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by jasminelmah** [lfabreti/convenience#7]
Hello! I am trying to run checkConvergence on some RevBayes output files that resulted from a single MCMC run. My log file was created was created with mnStochasticVariable(). It features the values for stochastic variables sampled from each iteration of the MCMC run. I also have a tree file which contains the posterior, likelihood, prior, and topology of each tree drawn from the posterior distribution. 

My command is: `CheckConvergence(list_files=c("output.log", "tree_file.trees"), format="revbayes", control)`

The error I get at the "Analyzing continuous parameters" step is:
> Error in if (var(my_runs[[i]]$ptable[j]) == 0) { : 
>   missing value where TRUE/FALSE needed

Do you know where I can start to debug this? Thanks for your help!

**Comment by lfabreti** [comment]
Dear jasminelmah, 

I wasn't able to reproduce your exact error, but I noticed you didn't provide the `control` variable.
Could you send me the command you used to generate `control`?

Best regards,
Luiza

**Comment by jasminelmah** [comment]
Thanks for getting back to me Luiza.

It wasn't clear to me how to use `control` from the RevBayes tutorial, so I think I probably misused it. Having said that, here's the command with `makeControl` and it still leads to the same error at the `Analyzing continuous parameters` step.

> check <- checkConvergence(list_files=c("output.log","tree_file.trees"), format="revbayes", control = makeControl(tracer=TRUE, burnin=0, precision=0.01))

**Comment by lfabreti** [comment]
Dear Jasmine, 

I'm sorry it took me so long to get back at you.
I tried the `makeControl` function as you used for an example run that I have, I didn't get any error.
Could you provide me with your output run?


Cheers, 
Luiza

**Comment by jasminelmah** [comment]
Hi Luiza,

I would be happy to share my output files. However, the data is not
published. Would it be possible to send them to a private email address? If
so, what address can I use?

I would be happy to post the solution to GitHub if we figure out what's
going on.

Cheers,
Jasmine

**Comment by jasminelmah** [comment]
Hi Luiza,

I think I figured out my problem. I had a column for topology in my log file. This column was populated by the trees in newick format. Removing this allowed `checkConvergence` to run!

I noticed that for `object$tree_parameters$frequencies`, there were 190 entries, but for `object$tree_parameters$ess` there were only 3. Is this expected behaviour?

Thanks for your help!

Cheers,
Jasmine

**Comment by lfabreti** [comment]
Hello Jasmine, 

I'm glad you could figure out the problem and run `checkConvergence`!

The behavior you observed is expected, because we don't calculate the ESS for splits with a frequency higher than 0.975 or lower than 0.025. 
The ESS methods don't perform well for very high or very low frequencies.
You can observe that in Figure 4 in the paper [https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13727](url).

I'm happy to help if you have further questions!

Best,
Luiza

**Comment by jasminelmah** [comment]
Hi Luiza,

Thanks for pointing me towards Fig. 4! Your explanation makes total sense - there are a lot of splits with 1s. 

Thank you very much for your help! Much appreciated.

Cheers,
Jasmine
